//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CacheRefreshSettings
    {
        public int RefreshId { get; set; }
        public string RefreshSPName { get; set; }
        public System.DateTime RefreshDateTime { get; set; }
    }
}
