//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NZNameAndAddressMaster
    {
        public int AddressId { get; set; }
        public string accountcode { get; set; }
        public string na_type { get; set; }
        public string na_name { get; set; }
        public string na_company { get; set; }
        public string na_street { get; set; }
        public string na_suburb { get; set; }
        public string na_country { get; set; }
        public string na_address_6 { get; set; }
        public string na_address_7 { get; set; }
        public string postcode { get; set; }
        public string na_country_code { get; set; }
        public string na_phone { get; set; }
        public string na_mobile_phone { get; set; }
        public string na_fax_no { get; set; }
        public string na_company_id { get; set; }
    }
}
