//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POApproval
    {
        public int ApprovalId { get; set; }
        public string ApprovedBy { get; set; }
        public System.DateTime ApprovedOn { get; set; }
        public int PONum { get; set; }
        public string POSuffix { get; set; }
        public string CountryCode { get; set; }
    }
}
