//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderStatusDesc
    {
        public int POStatusDescID { get; set; }
        public string posd_status { get; set; }
        public string posd_language { get; set; }
        public string posd_description { get; set; }
    }
}
