//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKCreMaster
    {
        public int CreMasterId { get; set; }
        public string cre_accountcode { get; set; }
        public string cr_pay_to_code { get; set; }
        public string cr_shortname { get; set; }
        public double cr_opening_bal { get; set; }
        public double cr_balance { get; set; }
        public double cr_future_amt { get; set; }
        public double cr_purchase_ytd { get; set; }
        public string cr_def_payment_terms { get; set; }
        public string PaymentTermDesc { get; set; }
        public string cr_payment_selection { get; set; }
        public string cr_auto_rq_flag { get; set; }
        public string cr_type { get; set; }
        public string cr_chq_or_bankdraft { get; set; }
        public string cr_account_status { get; set; }
        public string cr_clearing_flag { get; set; }
        public string cr_contact_name { get; set; }
        public string cr_default_gl_accountcode { get; set; }
        public Nullable<System.DateTime> cr_date_last_changed { get; set; }
        public string cr_curr_code { get; set; }
        public Nullable<System.DateTime> cr_date_created { get; set; }
    }
}
