//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKPurchaseOrderDeliveryArchive
    {
        public int PODeliveryId { get; set; }
        public int po_order_no { get; set; }
        public string po_backorder_flag { get; set; }
        public string po_dl_type { get; set; }
        public string po_dl_text_1 { get; set; }
        public string po_dl_text_2 { get; set; }
        public string po_dl_text_3 { get; set; }
        public string po_dl_text_4 { get; set; }
        public string po_dl_text_5 { get; set; }
        public string po_dl_text_6 { get; set; }
        public string po_dl_text_7 { get; set; }
        public string po_dl_postcode { get; set; }
        public string po_dl_country_code { get; set; }
        public string po_dl_phone { get; set; }
        public string po_dl_fax { get; set; }
        public string po_dl_address_id { get; set; }
        public string po_dl_ausbar_code { get; set; }
        public string po_dl_mobile_phone { get; set; }
        public string po_dl_email { get; set; }
    }
}
