//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKPurchaseOrder
    {
        public int PurchaseOrderId { get; set; }
        public int po_order_no { get; set; }
        public string po_backorder_flag { get; set; }
        public string cre_accountcode { get; set; }
        public Nullable<System.DateTime> po_order_date { get; set; }
        public Nullable<System.DateTime> po_action_date { get; set; }
        public Nullable<System.DateTime> po_arrival_date { get; set; }
        public Nullable<System.DateTime> po_received_date { get; set; }
        public string po_order_status { get; set; }
        public string po_order_terms { get; set; }
        public string po_inwards_no { get; set; }
        public string po_inwards_order_suffix { get; set; }
        public string po_whse_code { get; set; }
        public string po_receiving_whse { get; set; }
        public string po_currency_code { get; set; }
        public double po_initial_currency_rate { get; set; }
        public double po_final_currency_rate { get; set; }
        public double po_order_total { get; set; }
        public double po_received_total { get; set; }
        public double po_charges_total { get; set; }
        public double po_ordered_tax_amt { get; set; }
        public double po_received_tax_amt { get; set; }
        public int po_invoice_no { get; set; }
        public string po_invoice_details { get; set; }
        public Nullable<System.DateTime> po_invoice_date { get; set; }
        public double po_invoice_amount { get; set; }
        public double po_invoice_tax_amount { get; set; }
        public double po_normal_provision_amount { get; set; }
        public double po_specials_provision_amount { get; set; }
        public double po_charges_provision_amount { get; set; }
        public string po_vessel_name { get; set; }
        public string po_entry_port { get; set; }
        public string po_voyage_no { get; set; }
        public string po_lc_number { get; set; }
        public string po_shipment_no { get; set; }
        public Nullable<System.DateTime> po_costing_date { get; set; }
        public string po_notes { get; set; }
        public string po_job_no { get; set; }
        public string po_job_cost_centre { get; set; }
        public string o_po_quote_tax_exemption { get; set; }
        public double po_job_retention_amount { get; set; }
        public string po_user_name { get; set; }
        public Nullable<System.DateTime> po_date_stamp { get; set; }
        public System.DateTime po_time_stamp { get; set; }
        public string po_carrier_code { get; set; }
        public int po_drop_sales_order_no { get; set; }
        public short po_revision_no { get; set; }
        public string po_reason_code { get; set; }
        public string po_order_type { get; set; }
        public string po_confirmation_flag { get; set; }
        public string po_batch_ref { get; set; }
        public string po_receiver_user_id { get; set; }
        public string po_country_code { get; set; }
        public string po_misc_code { get; set; }
        public string po_tax_group { get; set; }
        public string po_control_lock { get; set; }
        public int po_control_user_lock { get; set; }
        public double po_total_weight { get; set; }
        public double po_total_qty { get; set; }
        public double po_total_volume { get; set; }
        public string po_original_edi_run { get; set; }
        public Nullable<System.DateTime> po_spare_date { get; set; }
        public int po_catalog_no { get; set; }
        public double po_spare_num { get; set; }
        public string po_spare_code { get; set; }
        public string po_qa_released { get; set; }
        public string po_user_only_alpha20_1 { get; set; }
        public int po_control_user_id_no { get; set; }
        public double po_header_tax_rate { get; set; }
        public string o_po_tax_classification_code { get; set; }
        public double po_max_retention_amount { get; set; }
        public double po_max_retention_percent { get; set; }
        public double po_max_retention_claim_percent { get; set; }
        public string po_next_claim_no { get; set; }
        public string po_line_format { get; set; }
        public string po_requisition_entry_user_name { get; set; }
        public string po_requisition_approval_user { get; set; }
        public double po_transit_total { get; set; }
        public double po_transit_tax_amt { get; set; }
        public double po_total_line_qty { get; set; }
        public string po_dif_flag { get; set; }
        public int Flag { get; set; }
        public bool ValidPO { get; set; }
        public bool Archived { get; set; }
    }
}
