//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKPurchaseOrderLineArchive
    {
        public int PurchaseOrderLineId { get; set; }
        public int po_order_no { get; set; }
        public string po_backorder_flag { get; set; }
        public double po_l_seq { get; set; }
        public string po_line_type { get; set; }
        public string po_charge_type { get; set; }
        public string po_price_override_flag { get; set; }
        public string stock_code { get; set; }
        public string po_supplier_stock_code { get; set; }
        public string po_line_description { get; set; }
        public double po_item_price { get; set; }
        public double pol_ordered_tax_amt { get; set; }
        public double po_disc_rate { get; set; }
        public double pol_spare_no_1 { get; set; }
        public double po_supplier_unit_of_measure { get; set; }
        public string po_supplier_unit_description { get; set; }
        public double po_supplier_unit_conversion { get; set; }
        public double po_order_qty { get; set; }
        public double po_received_qty { get; set; }
        public double po_backorder_qty { get; set; }
        public double pol_previous_line_cost { get; set; }
        public double po_received_total_amount { get; set; }
        public double po_order_line_total { get; set; }
        public string pol_gl_accountcode { get; set; }
        public Nullable<System.DateTime> po_line_date_expected { get; set; }
        public System.DateTime pol_time_expected { get; set; }
        public Nullable<System.DateTime> po_line_date_stamp { get; set; }
        public System.DateTime po_line_time_stamp { get; set; }
        public int requisition_no { get; set; }
        public string o_pol_tax_rate_code { get; set; }
        public double pol_tax_rate { get; set; }
        public double pol_received_tax_amt { get; set; }
        public double pol_link_to_seq_no { get; set; }
        public string o_pol_tax_exemptions { get; set; }
        public double pol_spare_num { get; set; }
        public double pol_tax_rate_included_in_cost { get; set; }
        public Nullable<System.DateTime> pol_user_only_date1 { get; set; }
        public string pol_user_only_alpha4_1 { get; set; }
        public string pol_user_only_alpha4_2 { get; set; }
        public double pol_user_only_num1 { get; set; }
        public double pol_user_only_num2 { get; set; }
        public double pol_in_transit_qty { get; set; }
        public double pol_in_transit_total { get; set; }
        public double pol_transit_tax_amt { get; set; }
        public string pol_non_stk_tax_code { get; set; }
        public double pol_received_tax_inc_in_cost { get; set; }
        public string SpexLink { get; set; }
        public string SpexStatus { get; set; }
        public string ArtworkLink { get; set; }
        public string ArtworkStatus { get; set; }
        public int Flag { get; set; }
        public bool ValidPOL { get; set; }
        public bool Archived { get; set; }
    }
}
