//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UKStockMaster
    {
        public int StockId { get; set; }
        public string stock_code { get; set; }
        public string stock_group { get; set; }
        public string stk_abc_class { get; set; }
        public string stk_stock_status { get; set; }
        public string stk_issue_control_code { get; set; }
        public string stk_condition_code { get; set; }
        public short stk_indicator { get; set; }
        public string stk_cyclic_code { get; set; }
        public string stk_user_group_1 { get; set; }
        public string stk_user_group_2 { get; set; }
        public string stk_description { get; set; }
        public string stk_desc_line_2 { get; set; }
        public string stk_desc_line_3 { get; set; }
        public string stk_unit_desc { get; set; }
        public double stk_pack_weight { get; set; }
        public string stk_pack_desc { get; set; }
        public double stk_pack_qty { get; set; }
        public double stk_pack_cubic_size { get; set; }
        public double stk_conversion_factor { get; set; }
        public string stk_alt_unit_desc { get; set; }
        public string stk_apn_number { get; set; }
        public string stk_import_tariff_code { get; set; }
        public string stk_serialized_flag { get; set; }
        public string stk_storage_type_flag { get; set; }
        public double stk_std_cost { get; set; }
        public double stk_replacement_cost { get; set; }
        public double stk_sales_cost { get; set; }
        public double stk_duty_paid_cost { get; set; }
        public double stk_info_cost { get; set; }
        public short stk_shelf_life_days { get; set; }
        public string stk_warranty_type_flag { get; set; }
        public Nullable<System.DateTime> stk_date_last_change { get; set; }
        public int stk_price_per { get; set; }
        public string stk_reorder_policy { get; set; }
        public string stk_reorder_review { get; set; }
        public string stk_reorder_buyer { get; set; }
        public Nullable<System.DateTime> stk_creation_date { get; set; }
        public string stk_movement_code { get; set; }
        public string stk_sales_type_code { get; set; }
        public double stk_sales_tax_paid_rate { get; set; }
        public string stk_sort_analysis_code { get; set; }
        public double stk_exise_qty { get; set; }
    }
}
