//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProductSpecification
    {
        public string ProductCode { get; set; }
        public string Prod_Desc { get; set; }
        public string Specification_No { get; set; }
        public string Revision_No { get; set; }
        public string Spec_Status { get; set; }
        public string excel_suppliername { get; set; }
        public string sid { get; set; }
        public string Series_NO { get; set; }
    }
}
