//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VQCPurchaseOrderDetail
    {
        public int PONum { get; set; }
        public string POSuffix { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<double> QtyOrdered { get; set; }
        public string po_order_status { get; set; }
        public string posd_description { get; set; }
        public string EAGTIN { get; set; }
        public Nullable<int> EAQty { get; set; }
        public string INGTIN { get; set; }
        public Nullable<int> INQty { get; set; }
        public string OUGTIN { get; set; }
        public Nullable<int> OUQty { get; set; }
    }
}
