//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VStockDetailsWithGTINALL
    {
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public int PackQty { get; set; }
        public string PackDesc { get; set; }
        public string StratemCode { get; set; }
        public string StratemName { get; set; }
        public string EAGTIN { get; set; }
        public Nullable<int> EAQty { get; set; }
        public string INGTIN { get; set; }
        public Nullable<int> INQty { get; set; }
        public string OUGTIN { get; set; }
        public Nullable<int> OUQty { get; set; }
        public Nullable<int> PLQty { get; set; }
        public Nullable<decimal> EALength { get; set; }
        public Nullable<decimal> EAWidth { get; set; }
        public Nullable<decimal> EAHeight { get; set; }
        public Nullable<decimal> EAWeight { get; set; }
        public string StockCondition { get; set; }
        public string CountryCode { get; set; }
    }
}
