//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUKPurchaseOrderLineDetail
    {
        public int po_order_no { get; set; }
        public string po_backorder_flag { get; set; }
        public double po_l_seq { get; set; }
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
        public string PortDate { get; set; }
        public string Qty { get; set; }
        public string UOM { get; set; }
        public string ServiceChargeP { get; set; }
        public string UnitPrice { get; set; }
        public string Value { get; set; }
        public double LineAmount { get; set; }
        public Nullable<long> RowNum { get; set; }
    }
}
